name: flast_chat
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" # Updated to support Flutter 3.x and beyond

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies with compatible versions
  firebase_core: ^3.6.0 # Latest stable as of early 2025
  firebase_auth: ^5.3.1 # Latest stable as of early 2025
  cloud_firestore: ^5.4.4 # Latest stable as of early 2025

  # Other dependencies
  flutter_bloc: ^8.1.6 # Updated to latest stable in 8.x series
  modal_progress_hud_nsn: ^0.5.0
  animated_text_kit: ^4.2.2
  google_sign_in: ^6.2.1 # Updated to latest stable version

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
